title: "ML Architect Journey"
description: "A 90-day learning journal to master machine learning and architecture"
theme: minima
baseurl: ""
url: "https://sunilmusinada.github.io/mljourney.github.io"
markdown: kramdown
