title: "ML Architect Journey"
description: "A 90-day learning journal to master machine learning and architecture"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: ""
url: "https://sunilmusinada.github.io/mljourney.github.io"
markdown: kramdown
