title: "ML Architect Journey"
description: "A 90-day learning journal to master machine learning and architecture"
theme: minima
baseurl: ""
url: "https://<your-username>.github.io/ml-architect-journey"
markdown: kramdown
